k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  imageScans:
    enable: false
  ui:
    skin: Solarized-16
    headless: false
    logoless: true
    crumbsless: false
    noIcons: false
  readOnly: false
  noExitOnCtrlC: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  disablePodCounting: false
